/**
 * Books Data Access (Server-only)
 * @module lib/books/books-data-access.server
 * @description
 * Reads consolidated book data from PostgreSQL (generated by lib/books/generate.ts).
 * Provides the same public API as audiobookshelf.server.ts so consumer code only
 * changes its import path, not its function calls.
 *
 * Caching: Next.js Cache Components ("use cache") with cache tags and
 * revalidation windows aligned to healthy/fallback states.
 *
 * Error contract: Database connectivity errors surface via `isFallback: true` in
 * the public API return values. Callers can distinguish "successfully loaded books"
 * from "returning stale/empty data due to infrastructure failure."
 */

import "server-only";

import { readBooksFromDb } from "@/lib/db/queries/books";
import { envLogger } from "@/lib/utils/env-logger";
import { cacheContextGuards, USE_NEXTJS_CACHE, withCacheFallback } from "@/lib/cache";
import type { Book, BookListItem } from "@/types/schemas/book";

// ─────────────────────────────────────────────────────────────────────────────
// Cache TTLs
// ─────────────────────────────────────────────────────────────────────────────

const CACHE_TTL_MS = 60 * 60 * 1000; // 1 hour
const CACHE_RETRY_TTL_MS = 5 * 60 * 1000; // 5 minutes — shorter retry window after DB failure
const CACHE_TTL_SECONDS = CACHE_TTL_MS / 1000;
const CACHE_RETRY_TTL_SECONDS = CACHE_RETRY_TTL_MS / 1000;

async function loadBooksState(): Promise<{ books: Book[]; isFallback: boolean }> {
  try {
    const books = await readBooksFromDb();
    return { books, isFallback: false };
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error);
    envLogger.log("Failed to load books from database", { error: message }, { category: "Books" });
    return { books: [], isFallback: true };
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Cached Internal Implementation
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Cache-wrapped internal fetch with Next.js "use cache" directive.
 * Isolated so the directive is only activated when USE_NEXTJS_CACHE is true.
 */
async function fetchBooksCached(): Promise<{ books: Book[]; isFallback: boolean }> {
  "use cache";

  const state = await loadBooksState();

  // Keep cache revalidate aligned with healthy/fallback load outcomes.
  const revalidate = state.isFallback ? CACHE_RETRY_TTL_SECONDS : CACHE_TTL_SECONDS;
  cacheContextGuards.cacheLife("Books", { revalidate });
  cacheContextGuards.cacheTag("Books", "books-dataset");

  return state;
}

/**
 * Gate on USE_NEXTJS_CACHE following the established codebase pattern
 * (see bookmarks-data-access.server.ts:184-195 for reference).
 */
async function fetchBooksInternal(): Promise<{ books: Book[]; isFallback: boolean }> {
  return USE_NEXTJS_CACHE
    ? withCacheFallback(
        () => fetchBooksCached(),
        () => loadBooksState(),
      )
    : loadBooksState();
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API — same signatures as audiobookshelf.server.ts
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Fetch all books. Reports `isFallback: true` when DB load failed and data
 * is stale or empty.
 */
export async function fetchBooksWithFallback(
  _options?: Record<string, unknown>,
): Promise<{ books: Book[]; isFallback: boolean; fetchedAt: number }> {
  const { books, isFallback } = await fetchBooksInternal();
  return { books, isFallback, fetchedAt: 0 };
}

/**
 * Fetch all books (simple wrapper).
 * Used by sitemap.ts and other consumers that don't need fallback metadata.
 * Logs a warning when returning stale/fallback data so callers are aware.
 */
export async function fetchBooks(): Promise<Book[]> {
  const { books, isFallback } = await fetchBooksInternal();
  if (isFallback) {
    envLogger.log(
      "fetchBooks() returning stale/fallback data due to database failure",
      { bookCount: books.length },
      { category: "Books" },
    );
  }
  return books;
}

/**
 * Fetch a single book by ID. Reports `isFallback: true` when DB load failed.
 */
export async function fetchBookByIdWithFallback(
  id: string,
  _options?: Record<string, unknown>,
): Promise<{ book: Book | null; isFallback: boolean }> {
  const { books, isFallback } = await fetchBooksInternal();
  const book = books.find((b) => b.id === id) ?? null;
  return { book, isFallback };
}

/**
 * Fetch minimal book list items. Reports `isFallback: true` when DB load failed.
 */
export async function fetchBookListItemsWithFallback(
  _options?: Record<string, unknown>,
): Promise<{ books: BookListItem[]; isFallback: boolean; fetchedAt: number }> {
  const { books, isFallback } = await fetchBooksInternal();
  const items: BookListItem[] = books.map(({ id, title, authors, coverUrl, coverBlurDataURL }) => ({
    id,
    title,
    authors,
    coverUrl,
    coverBlurDataURL,
  }));
  return { books: items, isFallback, fetchedAt: 0 };
}

/**
 * Invalidate the cached books dataset tag.
 * This intentionally avoids any process-lifetime cache state.
 */
export function clearBooksCache(): void {
  cacheContextGuards.revalidateTag("Books", "books-dataset");
}
